export PYTHONPATH=..
python3 DfaDef.py &&
python3 DfaAcpt.py &&
python3 Reachable.py &&
python3 MinDFA.py &&
python3 RenumberDFA.py &&
python3 StanNumDFA.py &&
python3 DfaToNfa.py &&
python3 ComplementDFA.py &&
python3 DFAtoRegx.py &&
python3 EqualDFA.py &&
python3 EquivDFA.py &&
python3 DfaEquivNfa.py &&
python3 NfaDef.py &&
python3 EClosure.py &&
python3 NfaToDfa.py &&
python3 NfaAcpt.py &&
python3 NFAtoRegx.py &&
python3 RenumberNFA.py &&
python3 EquivNfa.py &&
python3 NfaEquivDfa.py &&
python3 RegxConstructor.py &&
python3 PrimRegxGen.py &&
python3 RegxOp.py &&
python3 RegxStar.py &&
python3 RegxMix.py &&
python3 RegxToNfa.py &&
python3 RegxToDfa.py &&
python3 RegxEquiv.py && echo 'Great success!'
